version: '3.8'

services:
  paste:
    image: ghcr.io/lucko/paste

  bytebin:
    image: ghcr.io/lucko/bytebin
    volumes:
      - data:/opt/bytebin/content
    environment:
      BYTEBIN_MISC_KEYLENGTH: 5

  nginx:
    image: nginx:alpine
    command: ['nginx', '-g', 'daemon off;']
    depends_on:
      - paste
      - bytebin
    ports:
      - 1020:80
    volumes:
      - ./docker/reverseproxy-nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  data: {}
